name: DeployPlugin
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: FriendsOfShopware/actions/.github/workflows/github.yml@main
    with:
      extensionName: ${{ github.event.repository.name }}
    secrets:
      ghToken: ${{ secrets.GITHUB_TOKEN }}
